### ISSUE TITLE
Incompatible with using Revise

### ISSUE THREAD

**Issue by BeastyBlacksmith** [BeastyBlacksmith/ProtoStructs.jl#13]
using ProtoStucts when Revise is loaded errors on method deletion.

Can't reproduce yet. More info needed.

**Comment by BeastyBlacksmith** [comment]
A bit unclear if #31 fixed this

**Comment by Eben60** [comment]
I'm not sure if I have the same error: here a way to reproduce it (Julia 1.10 on Apple Silicon).

Create a file `"src/ProtoTest.jl"`:
```
using ProtoStructs

@proto struct Foo
    x :: Int
    # y :: Int
end
```
In a fresh Julia session:
```
julia> using Revise; includet("src/ProtoTest.jl")
```
Now uncomment the "y-line" in `"src/ProtoTest.jl"` and save it.

```
julia> Foo(42, 43)
┌ Error: Failed to revise /Users/.../ProtoTest.jl
│   exception =
│    AssertionError: ld[idx] < typemax(eltype(ld))
│    Stacktrace:
```

**Comment by Tortar** [comment]
I guess the problem is with the macro re-evaluation e.g. this works

```julia
using ProtoStructs

eval(@macroexpand @proto struct Foo
    x :: Int
    y :: Int
end)

```

**Comment by BeastyBlacksmith** [comment]
> julia> Foo(42, 43)
> ┌ Error: Failed to revise /Users/.../ProtoTest.jl
> │   exception =
> │    AssertionError: ld[idx] < typemax(eltype(ld))
> │    Stacktrace:
> │     [1] (::Revise.var"#76#78"{OrderedCollections.OrderedDict{Revise.RelocatableExpr, Union{Nothing, Vector{Any}}}, OrderedCollections.OrderedDict{Revise.RelocatableExpr, Union{Nothing, Vector{Any}}}})()
> │       @ Revise ~/.julia/packages/Revise/FaTes/src/packagedef.jl:269
> └ @ Revise ~/.julia/packages/Revise/FaTes/src/packagedef.jl:724

@TimHoly excuse me to ping you like this, but do you happen to know which assumption I am violating here?
