### ISSUE TITLE
mutable structs?

### ISSUE THREAD

**Issue by SteffenPL** [BeastyBlacksmith/ProtoStructs.jl#6]
Is it possible to extend this for mutable structs? 
(I guess the straightforward answers, not really since it uses `NamedTuples`. Feel free to close the issue directly.)

Anyway, the package is super cool :D  thanks a lot...

**Comment by BeastyBlacksmith** [comment]
Well, we could use a `Dict` instead of a `NamedTuple` and do the same. PRs welcome :)

**Comment by SteffenPL** [comment]
Cool, I will work on a PR for that next week.

**Comment by SteffenPL** [comment]
Instead of `Dict`, we could also use https://github.com/MasonProtter/MutableNamedTuples.jl, which is probably faster and makes it a bit easier to get type stability.

Do you mind a new dependency in the PR?

**Comment by BeastyBlacksmith** [comment]
Small dependencies as this one are fine

**Comment by SteffenPL** [comment]
Hi,
I found this repository which implements `@redef` for immutable and mutable structs: https://github.com/FedericoStra/RedefStructs.jl
(Their approach is a bit simpler: they just generate a random name and a link to the current name.)

Since that works for me, I would use that repo instead.

**Comment by BeastyBlacksmith** [comment]
I'll keep this open as a reminder

**Comment by zot** [comment]
I like ProtoStructs' approach better because it keeps the type's identity:

```
julia> @proto struct B x end

julia> x = B(1)
B{NamedTuple{(:x,), Tuple{Any}}}(NamedTuple{(:x,), Tuple{Any}}((1,)))

julia> @proto struct B x; y end

julia> y = B(1,2)
B{NamedTuple{(:x, :y), Tuple{Any, Any}}}(NamedTuple{(:x, :y), Tuple{Any, Any}}((1, 2)))

julia> x isa B
true

julia> y isa B
true
```

but

```
julia> @redef struct A x end

julia> x = A(1)
A(1)

julia> @redef struct A x; y end

julia> y = A(1,2)
A(1, 2)

julia> x isa A
false

julia> y isa A
true
```
